//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeProjektima.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpravljanjeProjektima.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Datum početka ne može biti veći od datuma završetka..
        /// </summary>
        internal static string DatumProjektaError
        {
            get
            {
                return ResourceManager.GetString("DatumProjektaError", resourceCulture);
            }
        }

        internal static string WorkerDatesError
        {
            get
            {
                return ResourceManager.GetString("WorkersDateError", resourceCulture);
            }
        }

        internal static string WorkerJobError
        {
            get
            {
                return ResourceManager.GetString("WorkersJobError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected method call..
        /// </summary>
        internal static string MethodCallExpected {
            get {
                return ResourceManager.GetString("MethodCallExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan unos..
        /// </summary>
        internal static string NeispravanUnos {
            get {
                return ResourceManager.GetString("NeispravanUnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema podataka..
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dupli unos..
        /// </summary>
        internal static string NoDuplicates {
            get {
                return ResourceManager.GetString("NoDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string Osoba_ImeOsobe {
            get {
                return ResourceManager.GetString("Osoba_ImeOsobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OIB.
        /// </summary>
        internal static string Osoba_OIB {
            get {
                return ResourceManager.GetString("Osoba_OIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string Osoba_PrezimeOsobe {
            get {
                return ResourceManager.GetString("Osoba_PrezimeOsobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba je već dodijeljena projektu..
        /// </summary>
        internal static string OsobaVecRadiNaProjektu {
            get {
                return ResourceManager.GetString("OsobaVecRadiNaProjektu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum početka.
        /// </summary>
        internal static string Projekt_DatPocetka {
            get {
                return ResourceManager.GetString("Projekt_DatPocetka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum završetka.
        /// </summary>
        internal static string Projekt_DatZavrsetka {
            get {
                return ResourceManager.GetString("Projekt_DatZavrsetka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        internal static string Projekt_NazProjekta {
            get {
                return ResourceManager.GetString("Projekt_NazProjekta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string Projekt_OpisProjekta {
            get {
                return ResourceManager.GetString("Projekt_OpisProjekta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        internal static string Projekt_SifProjekta {
            get {
                return ResourceManager.GetString("Projekt_SifProjekta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected property expression..
        /// </summary>
        internal static string PropertyExpected {
            get {
                return ResourceManager.GetString("PropertyExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga osobe nije ispravna..
        /// </summary>
        internal static string UlogaNijeIspravna {
            get {
                return ResourceManager.GetString("UlogaNijeIspravna", resourceCulture);
            }
        }
    }
}
