//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeProjektima.Dal
{
    using System;
    using System.Collections.Generic;

    public partial class Assignment
    {

        public int ID { get; set; }
        public string Task { get; set; }
        public string Description { get; set; }
        public System.DateTime Start_date { get; set; }
        public System.DateTime End_date { get; set; }
        public string Status { get; set; }
        public int ID_Individual { get; set; }
        public int ID_Worker { get; set; }
        public int ID_Assigner { get; set; }
    
        public virtual Person Person { get; set; }  //  W
        public virtual Individual Individual { get; set; }
        public virtual Person Person1 { get; set; } //  A
    }
}
