//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeProjektima.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BTVDataContext : DbContext
    {
        public BTVDataContext()
            : base("name=BTVDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Class_T> Class_T { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Family_t> Family_t { get; set; }
        public virtual DbSet<Genus_t> Genus_t { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Individual> Individuals { get; set; }
        public virtual DbSet<Kingdom_t> Kingdom_t { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Order_t> Order_t { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Phylum_t> Phylum_t { get; set; }
        public virtual DbSet<Sensor> Sensors { get; set; }
        public virtual DbSet<Species_t> Species_t { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
