//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeProjektima.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Individual()
        {
            this.Assignments = new HashSet<Assignment>();
        }
    
        public int ID { get; set; }
        public string Notes { get; set; }
        public string Health { get; set; }
        public string Location { get; set; }
        public int ID_Species { get; set; }
        public int ID_Location { get; set; }
        public int ID_Kingdom { get; set; }
        public Nullable<int> ID_Sensor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual Kingdom_t Kingdom_t { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Sensor Sensor { get; set; }
        public virtual Species_t Species_t { get; set; }
    }
}
