//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeProjektima.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        public Osoba()
        {
            this.UlogaOsobe = new HashSet<UlogaOsobe>();
        }
    
        public int IdOsobe { get; set; }
        public string PrezimeOsobe { get; set; }
        public string ImeOsobe { get; set; }
        public string OIB { get; set; }
    
        public virtual ICollection<UlogaOsobe> UlogaOsobe { get; set; }
    }
}
