//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeProjektima.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekt
    {
        public Projekt()
        {
            this.UlogaOsobe = new HashSet<UlogaOsobe>();
        }
    
        public string SifProjekta { get; set; }
        public string NazProjekta { get; set; }
        public string OpisProjekta { get; set; }
        public Nullable<System.DateTime> DatPocetka { get; set; }
        public Nullable<System.DateTime> DatZavrsetka { get; set; }
    
        public virtual ICollection<UlogaOsobe> UlogaOsobe { get; set; }
    }
}
