//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeProjektima.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UlogaOsobe
    {
        public string SifProjekta { get; set; }
        public int IdOsobe { get; set; }
        public int IdUloge { get; set; }
        public System.DateTime DatDodjele { get; set; }
    
        public virtual Osoba Osoba { get; set; }
        public virtual Projekt Projekt { get; set; }
        public virtual Uloga Uloga { get; set; }
    }
}
