//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeProjektima.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uloga
    {
        public Uloga()
        {
            this.UlogaOsobe = new HashSet<UlogaOsobe>();
        }
    
        public int IdUloge { get; set; }
        public string NazUloge { get; set; }
    
        public virtual ICollection<UlogaOsobe> UlogaOsobe { get; set; }
    }
}
